"""added profile pic

Revision ID: 3432684c4c00
Revises: 6c8423eb804b
Create Date: 2023-01-11 18:04:55.592217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3432684c4c00'
down_revision = '6c8423eb804b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_pic')

    # ### end Alembic commands ###
